# Generated by Django 5.1.7 on 2025-04-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
