# Generated by Django 5.1.7 on 2025-04-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_calendarevent_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='end_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='start_time',
            field=models.CharField(max_length=100),
        ),
    ]
